set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CXX_FLAGS_INIT "-stdlib=libstdc++")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-stdlib=libstdc++")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-stdlib=libstdc++")