name: CMake CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release, RelWithDebInfo]
        include:

          # Linux GCC
          - os: ubuntu-24.04
            compiler: gcc
            cc: gcc
            cxx: g++

          # Linux Clang
          - os: ubuntu-24.04
            compiler: clang
            cc: clang
            cxx: clang++

          # Windows MSVC
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl

          # macOS AppleClang
          - os: macos-latest
            compiler: appleclang
            cc: clang
            cxx: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Install Ninja on Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y ninja-build

      # Setup MSVC environment
      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure