name: CMake CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-latest ]
        build_type: [ Debug, Release, RelWithDebInfo ]
        include:
          # Linux GCC
#          - os: ubuntu-24.04
#            compiler: gcc
#            cc: gcc-14
#            cxx: g++-14

          # Linux Clang
          - os: ubuntu-24.04
            compiler: clang
            cc: clang-19
            cxx: clang++-19

          # Windows MSVC
#          - os: windows-latest
#            compiler: msvc
#            cc: cl
#            cxx: cl
    steps:
      - uses: actions/checkout@v4

      # Install Ninja on Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-19 clang-tools-19 clang-format-19 clang-tidy-19 libc++-dev libc++abi-dev ninja-build gcc-14 g++-14

      # Setup MSVC environment
#      - name: Setup MSVC
#        if: runner.os == 'Windows'
#        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=clang-19 \
            -DCMAKE_CXX_COMPILER=clang++-19 \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_FLAGS="-stdlib=libc++"

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure