name: CMake CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-latest, macos-latest ]
        compiler: [ gcc, clang, msvc, apple-clang ]
        build_type: [ Debug, Release, RelWithDebInfo ]
        include:
          # Linux GCC
          - os: ubuntu-24.04
            compiler: gcc
            cc: gcc-14
            cxx: g++-14
            flag: libc++

          # Linux Clang
          - os: ubuntu-24.04
            compiler: clang
            cc: clang-19
            cxx: clang++-19
            flag: libstdc++

          # Windows MSVC
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl

          # macOS Clang
          - os: macos-latest
            compiler: apple-clang
            cc: clang
            cxx: clang++
            build_type: Release

          # macOS GCC
          - os: macos-latest
            compiler: apple-clang
            cc: gcc
            cxx: g++

        exclude:
          - os: ubuntu-24.04
            compiler: msvc
          - os: ubuntu-24.04
            compiler: apple-clang
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: windows-latest
            compiler: apple-clang
          - os: macos-latest
            compiler: msvc

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ninja cmake llvm gcc clang-format

      # Install Ninja on Linux
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-19 clang-tools-19 clang-format-19 clang-tidy-19 libc++-dev libc++abi-dev ninja-build gcc-14 g++-14

        # Setup MSVC environment
      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        shell: bash
        run: |
          CLANG_CXX_FLAGS=""
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            CLANG_CXX_FLAGS="-DCMAKE_CXX_FLAGS=-stdlib=${{ matrix.flag }}"
          fi
          
          cmake -S . -B build -G Ninja \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            ${CLANG_CXX_FLAGS}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure